version: "3.2"
services:
  rabbitmq:
    image: 'rabbitmq:3.12.12-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - 5672:5672
      - 15672:15672
